import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { PostProvider } from "@/context/PostContext";
// import { QueryClientProvider } from "@tanstack/react-query";
// import localFont from "next/font/local";
import { Ubuntu_Mono } from "next/font/google";

const ubuntu = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
})



// const geistSans = Geist({
//   variable: "--font-ubuntu-mono",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {/* <QueryClientProvider>{children}</QueryClientProvider> */}
        <PostProvider>{children}</PostProvider>
      </body>
    </html>
  );
}
